### ISSUE TITLE
Corebird never removes unread notification on DMs button

### ISSUE THREAD

**Issue by Lyude** [baedert/corebird#342] opened 2015-03-30 14:21 UTC
Whenever I go to check a DM I got on Twitter, the little blue dot on the icon never goes away even after clicking the button.

**Comment by baedert** [comment] 2015-03-30 14:26
Dup of #236? The dot should only go away if you really open the right conversation, not just when you open the DM page. I have a few reports of that problem but I was unable to reproduce it so far.

**Comment by Lyude** [comment] 2015-03-30 14:41
I can reproduce it perfectly over here. Just had a couple of people DM me, and going to their conversation threads didn't remove the DMs.

**Comment by baedert** [comment] 2015-03-30 15:07
Well, did you already have a conversation with the sender of the DM, did you have unread DMs when starting corebird, did you have the conversation open when the DM arrived or not, did you have the DM threads page open or not etc. :)

**Comment by Lyude** [comment] 2015-03-30 15:23
Okay so, pretty sure it doesn't make a difference if the person has DMd me in the past or not. The conversation isn't open when the DM arrives.

**Comment by baedert** [comment] 2015-03-30 16:53
I feel like there's something fishy about this, but I just added some debugging output.

**Comment by Lyude** [comment] 2015-03-30 17:50
Ugh, it looks like you were right, there was something fishy. It looks like if I get the DM when I'm not in the DMs window it works fine, but if I'm in the DMs window then it doesn't work properly. So, when I am in the DMs window this is what comes up in the debug log:

```
Mar 30 13:48:50 meerkat org.baedert.corebird[3441]: ** (corebird:5072): DEBUG: DMThreadsPage.vala:411: unread_count -= 0
```

**Comment by Lyude** [comment] 2015-03-30 17:59
Or not. I'm having people try it with Corebird again and it looks like it's not happening on the main window now that I look at it.
Would it be possible for you to add some sort of feature to delete threads in the DM window so I can debug this a bit more easily?

**Comment by baedert** [comment] 2015-03-30 18:13
You can only delete single messages using the API (and that's rate limited...) :/

**Comment by gauravdighe** [comment] 2015-06-04 05:35
Is there a way to integrate CoreBird Notifications with GNOME3.16 notifications?

**Comment by baedert** [comment] 2015-06-04 05:50
Not that this is the right place to ask, but corebird already uses desktop notifications. I.e. if you haven't disabled it you should already get a desktop notification for incoming DMs.

**Comment by jc00ke** [comment] 2016-05-12 16:35
I'm not sure if it's related, but the unread notification for mentions doesn't go away either after I go to the mentions tab.

**Comment by baedert** [comment] 2016-05-12 17:16
That's unrelated, but you are talking about master, right?

**Comment by jc00ke** [comment] 2016-05-12 17:21
Yes, master.

**Comment by baedert** [comment] 2016-09-14 15:17
I'm not a big user of direct messages, is this still happening to anyone?

**Comment by jc00ke** [comment] 2016-09-14 19:19
The little blue dot disappears now when all of the unread DMs are read.

**Comment by baedert** [comment] 2016-09-15 10:47
ok, closing this then.

**Closed by baedert** 2016-09-15 10:47 UTC
