### ISSUE TITLE
FreeBSD - CoreBird doesn't open browser when "Request Pin" is clicked

### ISSUE THREAD

**Issue by ryansyah** [baedert/corebird#813] opened 2018-02-01 20:56 UTC
Hello Corebird Devs,

I have installed Corebird-1.73 from the ports tree on my FreeBSD 11.1 system. This a graphical workstation that runs Fluxbox, not Gnome.

Bug: When I hit the "Request Pin" button, I do not get a web browser tab opened to twitter asking me to allow this 3rd party app access to my login. Also, the 'Don't have a Twitter account yet?' link does not function.

It seems this problem has been brought up a few times already here, but none of the solutions I have seen so far work. I am not seeing any relevant messages from my terminal:
```
(corebird:117): Gtk-WARNING **: Theme parsing error: style.css:20:13: The 'icon-shadow' property has been renamed to '-gtk-icon-shadow'

(corebird:117): Gtk-WARNING **: Theme parsing error: style.css:231:16: The 'outline-radius' property has been renamed to '-gtk-outline-radius'

(corebird:117): Gtk-WARNING **: Theme parsing error: style.css:237:19: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(corebird:117): Gtk-WARNING **: Theme parsing error: style.css:238:25: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(corebird:117): Gtk-WARNING **: Theme parsing error: style.css:243:36: The :insensitive pseudo-class is deprecated. Use :disabled instead.
```

Looking at previous issue #728: 

- `xdg-util` port installed, which provides `xdg-open` on FreeBSD. No change. Running `xdg-open https://www.twitter.com/` from the command line will open twitter.com in a new tab in my active firefox session.

- `gvfs` port installed. no change.

Any other suggestions?

**Comment by baedert** [comment] 2018-02-02 08:16
Can you try clicking a link when corebird is run with `G_MESSAGES_DEBUG=all corebird`? What browser do you expect to open?

**Comment by ryansyah** [comment] 2018-02-02 16:13
@baedert , thanks for the suggestion. Here is what I see:
```
$ G_MESSAGES_DEBUG=all corebird
(corebird:96676): Gtk-DEBUG: Connecting to session manager
(corebird:96676): Gtk-DEBUG: Failed to get the GNOME session proxy: The name org.gnome.SessionManager is not owned
(corebird:96676): Gtk-DEBUG: Failed to get the Xfce session proxy: The name org.xfce.SessionManager is not owned
(corebird:96676): Gtk-DEBUG: Failed to get an inhibit portal proxy: The name org.freedesktop.portal.Desktop is not owned
(corebird:96676): corebird-DEBUG: Corebird.vala:208: startup

(corebird:96676): Gtk-WARNING **: Theme parsing error: style.css:20:13: The 'icon-shadow' property has been renamed to '-gtk-icon-shadow'

(corebird:96676): Gtk-WARNING **: Theme parsing error: style.css:231:16: The 'outline-radius' property has been renamed to '-gtk-outline-radius'

(corebird:96676): Gtk-WARNING **: Theme parsing error: style.css:237:19: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(corebird:96676): Gtk-WARNING **: Theme parsing error: style.css:238:25: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(corebird:96676): Gtk-WARNING **: Theme parsing error: style.css:243:36: The :insensitive pseudo-class is deprecated. Use :disabled instead.
(corebird:96676): corebird-DEBUG: MainWindow.vala:482: Could not load geometry, account == null
```

When I hit 'Request PIN':

```
(corebird:96676): corebird-DEBUG: Creating stream for screen_name
```

I would expect a new tab to open in my running firefox session, but this does not occur.

**Comment by theGeekPirate** [comment] 2018-02-02 16:40
Same issue here as well

```
[dozn@desktop ~]$ G_MESSAGES_DEBUG=all corebird
(corebird:13604): Gtk-DEBUG: Connecting to session manager
(corebird:13604): Gtk-DEBUG: Failed to get the GNOME session proxy: The name org.gnome.SessionManager is not owned
(corebird:13604): Gtk-DEBUG: Failed to get the Xfce session proxy: The name org.xfce.SessionManager is not owned
(corebird:13604): Gtk-DEBUG: Failed to get an inhibit portal proxy: The name org.freedesktop.portal.Desktop is not owned
(corebird:13604): corebird-DEBUG: Corebird.vala:208: startup

(corebird:13604): Gtk-WARNING **: Theme parsing error: style.css:20:13: The 'icon-shadow' property has been renamed to '-gtk-icon-shadow'

(corebird:13604): Gtk-WARNING **: Theme parsing error: style.css:231:16: The 'outline-radius' property has been renamed to '-gtk-outline-radius'

(corebird:13604): Gtk-WARNING **: Theme parsing error: style.css:237:19: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(corebird:13604): Gtk-WARNING **: Theme parsing error: style.css:238:25: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(corebird:13604): Gtk-WARNING **: Theme parsing error: style.css:243:36: The :insensitive pseudo-class is deprecated. Use :disabled instead.
(corebird:13604): corebird-DEBUG: MainWindow.vala:482: Could not load geometry, account == null
(corebird:13604): corebird-DEBUG: Creating stream for screen_name
```

**Comment by baedert** [comment] 2018-02-02 16:45
the snapd stuff obviously only helps if you run corebird via snap. Who of you two is doing that?

**Comment by theGeekPirate** [comment] 2018-02-02 16:47
> obviously

Well, I just installed it because it had helped others, didn't look into the package contents since I don't really care.

Not using snap, and can also confirm this issue occurs with the latest version on Github.

**Comment by baedert** [comment] 2018-02-05 11:22
Did you login+logout since you installed/ran firefox or chromium? What does `xdg-settings get default-web-browser` print?

I don't get how both of your outputs don't include the URL at all, we are clearly printing it here: https://github.com/baedert/corebird/blob/master/src/widgets/AccountCreateWidget.vala#L64 so if we're not even getting here, the `request_token_async` call already failed (or rather: never completed)?

**Comment by theGeekPirate** [comment] 2018-02-05 11:59
```[dozn@desktop ~]$ xdg-settings get default-web-browser
chromium.desktop```

**Comment by baedert** [comment] 2018-02-05 14:08
That still doesn't make sense, if you use `G_MESSAGES_DEBUG=all`, we should print the URL we're attempting to open after the `request_token_async` call returns. The "Creating stream for screen_name" output indicates that https://github.com/baedert/corebird/blob/master/src/widgets/AccountCreateWidget.vala#L48 is getting executed. This just reminds me of the last issue in #804.

In any case, I can't reproduce any of it and you two seem to have the exact same problem but on wildly different systems.

**Comment by erikwesselius** [comment] 2018-02-07 12:57
I am experiencing exactly the same issue sas @theGeekPirate on a fully updated arch linux system, using Corebird 1.7.3-2

```
$ xdg-settings get default-web-browser
firefox.desktop
```
Here's my debug messages
```
G_MESSAGES_DEBUG=all corebird                    
(corebird:5929): Gtk-DEBUG: Connecting to session manager
(corebird:5929): Gtk-DEBUG: Failed to get the GNOME session proxy: The name org.gnome.SessionManager is not owned
(corebird:5929): Gtk-DEBUG: Failed to get the Xfce session proxy: The name org.xfce.SessionManager is not owned
(corebird:5929): Gtk-DEBUG: Failed to get an inhibit portal proxy: The name org.freedesktop.portal.Desktop is not owned
(corebird:5929): corebird-DEBUG: Corebird.vala:208: startup

(corebird:5929): Gtk-WARNING **: Theme parsing error: style.css:20:13: The 'icon-shadow' property has been renamed to '-gtk-icon-shadow'

(corebird:5929): Gtk-WARNING **: Theme parsing error: style.css:231:16: The 'outline-radius' property has been renamed to '-gtk-outline-radius'

(corebird:5929): Gtk-WARNING **: Theme parsing error: style.css:237:19: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(corebird:5929): Gtk-WARNING **: Theme parsing error: style.css:238:25: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(corebird:5929): Gtk-WARNING **: Theme parsing error: style.css:243:36: The :insensitive pseudo-class is deprecated. Use :disabled instead.
(corebird:5929): corebird-DEBUG: MainWindow.vala:482: Could not load geometry, account == null
(corebird:5929): corebird-DEBUG: Creating stream for screen_name
(corebird:5929): corebird-DEBUG: 0 Stopping screen_name's stream
```

**Comment by Vistaus** [comment] 2018-02-10 09:38
In this case I've got no clue whatsoever, so it may be a dumb suggestion, but what if you guys try to set a different default web browser? i.e. if it's currently Firefox, try to make Chromium or QupZilla or whatever default, if it's currently Chromium, try to make Firefox or QupZilla or whatever default. Does that solve the issue?

**Comment by cdietrich** [comment] 2018-02-12 07:02
that does not help. i believe it already steps out before

**Comment by erikwesselius** [comment] 2018-02-12 12:46
Same here: tested by choosing Chromium as default web browser (instead of FF Quantum), but that does not help.

**Comment by baedert** [comment] 2018-02-12 17:38
We have already concluded that *just* opening a browser can't be the problem here, it seems to be the `request_token_async` call not returning. For the browser opening problems, it would be more interesting to see what the "Don't have an Account yet? Create one" label does upon clicking that link. This should [show a warning](https://gitlab.gnome.org/GNOME/gtk/blob/gtk-3-22/gtk/gtklabel.c#L6732) when spawning the browser fails. Or at least if it fails *and* reports it back...

**Comment by alien2003** [comment] 2018-02-13 22:42
The same on Manjaro

**Comment by cdietrich** [comment] 2018-02-14 07:14
is there anything i can do to help investigating this? i already have cloned and built the code

**Comment by baedert** [comment] 2018-02-14 09:42
What does `G_MESSAGES_DEBUG=all corebird` print when you click the link in the "Don't have an Account yet? Create one" label?

**Comment by cdietrich** [comment] 2018-02-14 10:18
the create one open the browser as expected
```
(corebird:12950): Gtk-DEBUG: Connecting to session manager
(corebird:12950): Gtk-DEBUG: Failed to get the GNOME session proxy: The name org.gnome.SessionManager is not owned
(corebird:12950): corebird-DEBUG: Corebird.vala:208: startup

(corebird:12950): Gtk-WARNING **: Theme parsing error: style.css:20:13: The 'icon-shadow' property has been renamed to '-gtk-icon-shadow'

(corebird:12950): Gtk-WARNING **: Theme parsing error: style.css:231:16: The 'outline-radius' property has been renamed to '-gtk-outline-radius'

(corebird:12950): Gtk-WARNING **: Theme parsing error: style.css:237:19: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(corebird:12950): Gtk-WARNING **: Theme parsing error: style.css:238:25: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(corebird:12950): Gtk-WARNING **: Theme parsing error: style.css:243:36: The :insensitive pseudo-class is deprecated. Use :disabled instead.
(corebird:12950): corebird-DEBUG: MainWindow.vala:482: Could not load geometry, account == null

```

**Comment by erikwesselius** [comment] 2018-02-14 11:09
Exactly the same behaviour over here:

```
G_MESSAGES_DEBUG=all corebird
(corebird:6152): Gtk-DEBUG: Connecting to session manager
(corebird:6152): Gtk-DEBUG: Failed to get the GNOME session proxy: The name org.gnome.SessionManager is not owned
(corebird:6152): corebird-DEBUG: Corebird.vala:208: startup

(corebird:6152): Gtk-WARNING **: Theme parsing error: style.css:20:13: The 'icon-shadow' property has been renamed to '-gtk-icon-shadow'

(corebird:6152): Gtk-WARNING **: Theme parsing error: style.css:231:16: The 'outline-radius' property has been renamed to '-gtk-outline-radius'

(corebird:6152): Gtk-WARNING **: Theme parsing error: style.css:237:19: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(corebird:6152): Gtk-WARNING **: Theme parsing error: style.css:238:25: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(corebird:6152): Gtk-WARNING **: Theme parsing error: style.css:243:36: The :insensitive pseudo-class is deprecated. Use :disabled instead.
(corebird:6152): corebird-DEBUG: MainWindow.vala:482: Could not load geometry, account == null
```

**Comment by baedert** [comment] 2018-02-14 11:44
@cdietrich Since you've built corebird already: Go to the toplevel project directory and run
```bash
wget https://paste.xinu.at/anEOIr && git apply ./anEOIr
```

then compile. Then run that corebird version. First click Request PIN. Then click Retry.

**Comment by cdietrich** [comment] 2018-02-14 11:50
```
corebird-Message: All strings!
corebird-Message: Using POST https://api.twitter.com/oauth/request_token
corebird-Message: finish_call: Payload: oauth_token=<zensoed>&oauth_token_secret=<zensoed>&oauth_callback_confirmed=true
corebird-Message: _call_message_call_completed_cb: (nil)
(corebird:24367): corebird-DEBUG: Creating stream for screen_name
(corebird:24367): corebird-DEBUG: 0 Stopping screen_name's stream
corebird-Message: All strings!
corebird-Message: Using POST https://api.twitter.com/oauth/request_token
corebird-Message: finish_call: Payload: oauth_token=<zensoed>&oauth_token_secret=<zensoed>&oauth_callback_confirmed=true
corebird-Message: _call_message_call_completed_cb: (nil)
(corebird:24367): corebird-DEBUG: Creating stream for screen_name
(corebird:24367): corebird-DEBUG: 0 Stopping screen_name's stream
corebird-Message: All strings!
corebird-Message: Using POST https://api.twitter.com/oauth/request_token
corebird-Message: finish_call: Payload: oauth_token=<zensoed>&oauth_token_secret=<zensoed>&oauth_callback_confirmed=true
corebird-Message: _call_message_call_completed_cb: (nil)
```

**Comment by baedert** [comment] 2018-02-14 12:12
Just creates more mystery, but undo the last changes and then `wget https://paste.xinu.at/1KA2 && git apply 1KA2` please. Also, what valac version are you using and are you using the autotools or the meson build?

**Comment by cdietrich** [comment] 2018-02-14 12:31
i did just

```
./autogen.sh --prefix=/usr
make
``` 
as in readme

```
valac --version
Vala 0.38.6
``` 

and here is the log

```
corebird-Message: All strings!
corebird-Message: Using POST https://api.twitter.com/oauth/request_token
corebird-Message: finish_call: Payload: oauth_token=<zensored>&oauth_token_secret=<zensored>&oauth_callback_confirmed=true
corebird-Message: _call_message_call_completed_cb: (nil)
corebird-Message: request_token_cb 0x559ef94c5300
corebird-Message: request_token_cb: call_status: 1, error: (nil)
corebird-Message: oauth_proxy_call_parse_token_response 0x<zensored>
```

**Comment by baedert** [comment] 2018-02-14 15:49
And once again: `wget https://paste.xinu.at/Itg && git apply ./Itg`
Please don't censor the `0xf00bar` values as those are pointer addresses I need to compare.

It doesn't really make sense that we get [here](https://github.com/baedert/corebird/blob/master/src/rest/rest/oauth-proxy.c#L297) but the `g_task_return_boolean` call doesn't invoke the task's callback, which would ultimately return to the vala code in `AccountCreateWidget`.

**Comment by cdietrich** [comment] 2018-02-14 16:02
```
corebird-Message: oauth_proxy_request_token_async: Task: 0x55baa18a9820
corebird-Message: All strings!
corebird-Message: Using POST https://api.twitter.com/oauth/request_token
corebird-Message: finish_call: Payload: oauth_token=<zensored>&oauth_token_secret=<zensored>&oauth_callback_confirmed=true
corebird-Message: _call_message_call_completed_cb: (nil)
corebird-Message: request_token_cb 0x55baa15d5690
corebird-Message: request_token_cb: call_status: 1, error: (nil)
corebird-Message: oauth_proxy_call_parse_token_response 0x55baa15d5690
corebird-Message: oauth_proxy_call_parse_token_response: <zensored> <zensored> 1
corebird-Message: Calilng callback of task 0x55baa18a9820
corebird-Message: Task 0x55baa18a9820 destroyed
(corebird:26764): corebird-DEBUG: Creating stream for screen_name
(corebird:26764): corebird-DEBUG: 0 Stopping screen_name's stream
corebird-Message: oauth_proxy_request_token_async: Task: 0x55baa13291d0
corebird-Message: All strings!
corebird-Message: Using POST https://api.twitter.com/oauth/request_token
corebird-Message: finish_call: Payload: oauth_token=<zensored2>&oauth_token_secret=<zensored2>&oauth_callback_confirmed=true
corebird-Message: _call_message_call_completed_cb: (nil)
corebird-Message: request_token_cb 0x55baa1ff42f0
corebird-Message: request_token_cb: call_status: 1, error: (nil)
corebird-Message: oauth_proxy_call_parse_token_response 0x55baa1ff42f0
corebird-Message: oauth_proxy_call_parse_token_response: <zensored2> <zensored2> 1
corebird-Message: Calilng callback of task 0x55baa13291d0
corebird-Message: Task 0x55baa13291d0 destroyed
```

**Comment by baedert** [comment] 2018-02-14 16:30
Ooookay I can reproduce it now after downgrading to vala 0.38.6. Works with 0.38.7 though.

**Comment by baedert** [comment] 2018-02-14 16:35
Relevant bug report: https://bugzilla.gnome.org/show_bug.cgi?id=793158

**Comment by cdietrich** [comment] 2018-02-14 16:48
good to know. that version is already in the pipeline for manjaro http://manjaro.melbourneitmirror.net/testing/extra/x86_64/vala-0.38.7-1-x86_64.pkg.tar.xz

**Comment by cdietrich** [comment] 2018-02-14 17:17
i can confirm that building against this version helped

**Comment by ryansyah** [comment] 2018-02-14 18:37
Hey All,

I wanted to say thank you to everyone that has helped look at this issue so far.

vala version on my system:
`vala-0.36.10,1 `

Some additional indormation regarding recent vala commits to the FreeBSD ports tree:
https://www.freshports.org/lang/vala/

**Comment by baedert** [comment] 2018-02-14 18:59
@ryansyah Yes, I thought your original problem is basically unrelated to the vala breakage, since for you not even the "Create one" link worked. What does `xdg-settings get default-web-browser` print for you?

There are several other bug reports about links not working, but most of the recent ones are related to app distribution and unrelated to your issue. Things to try:

 - Also use `G_MESSAGES_DEBUG=all corebird` for all the tests
 - Does TAB'ing to the "Create one" link and hitting enter/return work?
 - Run `gtk3-demo --run=links`. Do those work?
 - If nothing else works, can you also use the `wget` command I posted earlier, recompile and retry?

**Comment by ryansyah** [comment] 2018-02-14 19:46
- What does `xdg-settings get default-web-browser` print for you?

Here is my xdg-settings output:
``` xdg-settings get default-web-browser 
userapp-Firefox-0NNZ2Y.desktop```

- Also use G_MESSAGES_DEBUG=all corebird for all the tests

Debug messages when running corebird are the same:
```
G_MESSAGES_DEBUG=all corebird
(corebird:20387): Gtk-DEBUG: Connecting to session manager
(corebird:20387): Gtk-DEBUG: Failed to get the GNOME session proxy: The name org.gnome.SessionManager is not owned
(corebird:20387): Gtk-DEBUG: Failed to get the Xfce session proxy: The name org.xfce.SessionManager is not owned
(corebird:20387): Gtk-DEBUG: Failed to get an inhibit portal proxy: The name org.freedesktop.portal.Desktop is not owned
(corebird:20387): corebird-DEBUG: Corebird.vala:208: startup

(corebird:20387): Gtk-WARNING **: Theme parsing error: style.css:20:13: The 'icon-shadow' property has been renamed to '-gtk-icon-shadow'

(corebird:20387): Gtk-WARNING **: Theme parsing error: style.css:231:16: The 'outline-radius' property has been renamed to '-gtk-outline-radius'

(corebird:20387): Gtk-WARNING **: Theme parsing error: style.css:237:19: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(corebird:20387): Gtk-WARNING **: Theme parsing error: style.css:238:25: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(corebird:20387): Gtk-WARNING **: Theme parsing error: style.css:243:36: The :insensitive pseudo-class is deprecated. Use :disabled instead.
(corebird:20387): corebird-DEBUG: MainWindow.vala:482: Could not load geometry, account == null
```

The 'Don't have an account yet?' section is greyed out and I am unable to click the blue 'create one' link. The only functional UI element is the 'Request PIN" button, which causes this debug output when pressed:
```
(corebird:30025): corebird-DEBUG: Creating stream for screen_name
```
The 'Confirm' button is greyed out, and whenI hit the 'Retry' button, I receive some additional debug out[put:
```
(corebird:30025): corebird-DEBUG: Creating stream for screen_name
```

- Does TAB'ing to the "Create one" link and hitting enter/return work?

OHAI! Why yes, yes it does. It appears to open `https://www.twitter.com/signup` in a new tab in my active Firefox session.

- Run `gtk3-demo --run=links`. Do those work?

When I run the command above, I am presented with a windows titled Application Class with a grey 'Run' button in the upper left hand side and a left aligned top to bottom list of items with a right aligned summary window for each item.

- If nothing else works, can you also use the wget command I posted earlier, recompile and retry?

I started with `anEOIr`, rebuilt, then ran `G_MESSAGES_DEBUG=all corebird`:
```
(corebird:89544): Gtk-DEBUG: Connecting to session manager
(corebird:89544): Gtk-DEBUG: Failed to get the GNOME session proxy: The name org.gnome.SessionManager is not owned
(corebird:89544): Gtk-DEBUG: Failed to get the Xfce session proxy: The name org.xfce.SessionManager is not owned
(corebird:89544): Gtk-DEBUG: Failed to get an inhibit portal proxy: The name org.freedesktop.portal.Desktop is not owned
(corebird:89544): corebird-DEBUG: Corebird.vala:208: startup

(corebird:89544): Gtk-WARNING **: Theme parsing error: style.css:20:13: The 'icon-shadow' property has been renamed to '-gtk-icon-shadow'

(corebird:89544): Gtk-WARNING **: Theme parsing error: style.css:231:16: The 'outline-radius' property has been renamed to '-gtk-outline-radius'

(corebird:89544): Gtk-WARNING **: Theme parsing error: style.css:237:19: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(corebird:89544): Gtk-WARNING **: Theme parsing error: style.css:238:25: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(corebird:89544): Gtk-WARNING **: Theme parsing error: style.css:243:36: The :insensitive pseudo-class is deprecated. Use :disabled instead.
(corebird:89544): corebird-DEBUG: MainWindow.vala:482: Could not load geometry, account == null
```

When I hit 'Request PIN', nothing happens outside of the debug output:
`(corebird:89544): corebird-DEBUG: Creating stream for screen_name`



One question I had not yet asked; Does Corebird depend or rely on any underlying gnome services to be running for proper functionality?

**Comment by baedert** [comment] 2018-02-14 20:33
> OHAI! Why yes, yes it does. It appears to open https://www.twitter.com/signup in a new tab in my active Firefox session.

Well, that explains why normal links don't work. Could be a WM issue similar to the one I found in Awesome 4 years back: https://github.com/baedert/corebird/issues/149. However, since you see the "Creating stream for screen_name" line, the `::clicked` handler of the button clearly runs.

> When I run the command above, I am presented with a window titled Application Class with a grey 'Run' button in the upper left hand side and a left aligned top to bottom list of items with a right aligned summary window for each item.

If you run with `--run=links`, it should open a second window containing a wrapping label with some links to click. You can get the same effect by just double-clicking the "Links" entry from the list on the left though. Shouldn't matter anymore however since we already concluded that links work, just not clicking them.

> I started with anEOIr, rebuilt, then ran G_MESSAGES_DEBUG=all corebird:

Are you sure you also `make install`'ed afterwards? Or, just run `src/corebird` instead of the installed version. Also, use `wget https://paste.xinu.at/Itg && git apply ./Itg` please, which is the latest version that adds some more debugging output.

> One question I had not yet asked; Does Corebird depend or rely on any underlying gnome services to be running for proper functionality?

No, at least not explicitly and not that I know of.

**Comment by ryansyah** [comment] 2018-02-14 20:58
reinstall:
```
#  pkg delete corebird
Updating database digests format: 100%
Checking integrity... done (0 conflicting)
Deinstallation has been requested for the following 1 packages (of 0 packages in the universe):

Installed packages to be REMOVED:
	corebird-1.7.3

Number of packages to be removed: 1

The operation will free 2 MiB.

Proceed with deinstalling packages? [y/N]: y
[1/1] Deinstalling corebird-1.7.3...
[1/1] Deleting files for corebird-1.7.3: 100%

# cd /usr/ports/net-im/corebird/
# make clean
===>  Cleaning for corebird-1.7.3
# make extract
===>  License GPLv3+ accepted by the user
===>   corebird-1.7.3 depends on file: /usr/local/sbin/pkg - found
===> Fetching all distfiles required by corebird-1.7.3 for building
===>  Extracting for corebird-1.7.3
=> SHA256 Checksum OK for baedert-corebird-1.7.3_GH0.tar.gz.
cd work/corebird-1.7.3/
# wget https://paste.xinu.at/Itg && git apply ./Itg
--2018-02-14 14:45:36--  https://paste.xinu.at/Itg
Resolving paste.xinu.at (paste.xinu.at)... 78.46.56.141, 2a01:4f8:201:2446::2
Connecting to paste.xinu.at (paste.xinu.at)|78.46.56.141|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5280 (5.2K) [text/x-diff]
Saving to: ‘Itg’

Itg                 100%[===================>]   5.16K  --.-KB/s    in 0s      

2018-02-14 14:45:37 (120 MB/s) - ‘Itg’ saved [5280/5280]
# cd ../../ && make install
<output omitted>
===>   Registering installation for corebird-1.7.3
```

Now let's run `G_MESSAGES_DEBUG=all corebird` and see what we can see:
```
(corebird:7177): Gtk-DEBUG: Connecting to session manager
(corebird:7177): Gtk-DEBUG: Failed to get the GNOME session proxy: The name org.gnome.SessionManager is not owned
(corebird:7177): Gtk-DEBUG: Failed to get the Xfce session proxy: The name org.xfce.SessionManager is not owned
(corebird:7177): Gtk-DEBUG: Failed to get an inhibit portal proxy: The name org.freedesktop.portal.Desktop is not owned
(corebird:7177): corebird-DEBUG: Corebird.vala:208: startup

(corebird:7177): Gtk-WARNING **: Theme parsing error: style.css:20:13: The 'icon-shadow' property has been renamed to '-gtk-icon-shadow'

(corebird:7177): Gtk-WARNING **: Theme parsing error: style.css:231:16: The 'outline-radius' property has been renamed to '-gtk-outline-radius'

(corebird:7177): Gtk-WARNING **: Theme parsing error: style.css:237:19: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(corebird:7177): Gtk-WARNING **: Theme parsing error: style.css:238:25: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(corebird:7177): Gtk-WARNING **: Theme parsing error: style.css:243:36: The :insensitive pseudo-class is deprecated. Use :disabled instead.
(corebird:7177): corebird-DEBUG: MainWindow.vala:482: Could not load geometry, account == null
````

- 'Request PIN' is clicked

```
(corebird:7177): corebird-DEBUG: Creating stream for screen_name
corebird-Message: oauth_proxy_request_token_async: Task: 0x810f0fc70
corebird-Message: All strings!
corebird-Message: Using POST https://api.twitter.com/oauth/request_token
corebird-Message: finish_call: Payload: oauth_token=0LppYAAAAAAANdM5AAABYZYbduQ&oauth_token_secret=pEw7coLuDDR0dSofJ71MLkiS7Fem2Zqm&oauth_callback_confirmed=true
corebird-Message: _call_message_call_completed_cb: 0x0
corebird-Message: request_token_cb 0x8110556e0
corebird-Message: request_token_cb: call_status: 1, error: 0x0
corebird-Message: oauth_proxy_call_parse_token_response 0x8110556e0
corebird-Message: oauth_proxy_call_parse_token_response: 0LppYAAAAAAANdM5AAABYZYbduQ pEw7coLuDDR0dSofJ71MLkiS7Fem2Zqm 1
corebird-Message: Calilng callback of task 0x810f0fc70
corebird-Message: Task 0x810f0fc70 destroyed
```

As before, no new tab is opened.

**Comment by baedert** [comment] 2018-02-15 17:41
Yeah, so the change in vala that broke the async function here not returning is also present in 0.36.10: https://git.gnome.org/browse/vala/commit/?h=0.36.10&id=3619229247b9cf503f8dafda5b7a8ebf6179c7c0 and fixed in 0.36.11: https://git.gnome.org/browse/vala/commit/?h=0.36.11&id=e99ce185f9228f23111e84f91d657e922ccfac6f m(

**Comment by ryansyah** [comment] 2018-02-15 20:14
Thanks @baedert for looking into this issue!
I've informed the vala port maintainers of this issue and have requested a version bump for vala to resolve the issue. I'll gladly report back here when that happens to confirm that the issue has been resolved.

**Comment by ryansyah** [comment] 2018-02-17 02:00
vala version bump for FreeBSD in progress. Upgraded to 0.36.12 in r462082.

Closing out this issue, will report back if I run into any other issues.

Have a good weekend!

**Comment by erikwesselius** [comment] 2018-02-19 10:31
I checked vala version (-.38.8) on my arch linux machine and recompiled. Authentication works fine now. Apparently I had compiled against one of the problematic vala versions. Thanks to all those who have helped to solve this issue, but first and foremost: thanks @baedert!

**Comment by baedert** [comment] 2018-02-19 19:05
Closing this then. Thanks for testing, everyone.

**Closed by baedert** 2018-02-19 19:05 UTC
