### ISSUE TITLE
nightly flatpak: "Request PIN" works, but also opens "Operation not supported" dialog

### ISSUE THREAD

**Issue by bastianilso** [baedert/corebird#711] opened 2017-04-26 13:10 UTC
When I press the "Request PIN" button from the flatpak nightly corebird, it opens both the URI portal, but also a dialog that says "operation not supported" and also writes a label in the main window stating "Could not open http://twitter.com/oauth/authorize?oauth_token=R-4uIAAAAAAANdM5AAABW6pfvmA".

Despite all of that, using the URI portal works fine, so those dialogs and labels seem a bit confusing.

![corebird-operation-not-supported](https://cloud.githubusercontent.com/assets/3967945/25436030/45a5f434-2a92-11e7-83c2-ad1c9649730d.png)

**Comment by baedert** [comment] 2017-04-26 13:30
Hmm, I can reproduce that even with the org.gnome.PortalTest test app, so nothing Corebird specific

**Comment by baedert** [comment] 2017-04-26 20:12
The stable version with the 3.22 runtime doesn't exhibit that behavior here so I assume that's a problem in glib

**Comment by baedert** [comment] 2017-04-26 20:47
Can you try installing `org.gnome.PortalTest` from https://github.com/matthiasclasen/portal-test ?
Then run it and click on the link. Try it once with `flatpak run org.gnome.PortalTest` and see if there's an "unable to show" warning on the console. Then try it again with `flatpak run --devel org.gnome.PortalTest`. Does it work without the warning now? I'd just like to get some confirmation before opening a bug against flatpak.

**Comment by bastianilso** [comment] 2017-04-27 08:04
I tried installing it, but I am running into some issues when trying to install portal-test. I have filed an issues against portal-test:
https://github.com/matthiasclasen/portal-test/issues/5

**Comment by baedert** [comment] 2017-04-29 12:16
It seems to be a problem where the return value of `gtk_show_uri_on_window` is `TRUE` but the `error` parameter is still set. That's why both vala's exception handling reports a failure as well as `GtkLinkButton`, which checks `error != NULL`. `GtkLabel` however checks the return value o the `gtk_show_uri_on_window` call which is `TRUE` and therefore does not even print a warning.

**Comment by baedert** [comment] 2017-04-29 15:42
This should be fixed by https://git.gnome.org/browse/glib/commit/?id=3e2187975d4d620630cc8c655d36a92ec423c632.

The `GtkLabel`'s inside tweets rows etc. do not exhibit this behavior thankfully. I'm closing this now, but plrease reopen if it persists beyond the next update of the nightly runtime.

**Closed by baedert** 2017-04-29 15:42 UTC
Labels: Flatpak
