### ISSUE TITLE
Inputbox not correctly scaled on tweets with images

### ISSUE THREAD

**Issue by HeikoAdams** [baedert/corebird#509] opened 2016-02-01 19:54 UTC
It looks like the inputbox is not correctly scaled if you try to quote or reply a tweet containing an image.
![bildschirmfoto vom 2016-02-01 20-54-12](https://cloud.githubusercontent.com/assets/1418818/12729233/fe475048-c925-11e5-8719-4e06e075b08a.png)

**Comment by HeikoAdams** [comment] 2016-02-01 19:55
I forgot: I'm running the latest git-master

**Comment by IBBoard** [comment] 2016-02-08 20:11
Looks like a duplicate of #458, which I reported a while ago.

The comment on 98ddce01fa8f3a100452e5af34db2c3954b2aa66 looks promising as a fix, but I've not tested it yet.

**Comment by Lyude** [comment] 2016-02-21 18:49
I would say we also need to add a limit for how large the window can get by default and scale the images/wrap the text down accordingly at that limit, that fix is a little too much: 
![screenshot from 2016-02-21 13-47-52](https://cloud.githubusercontent.com/assets/1527057/13204599/da8d1c6a-d8a1-11e5-9767-49570c8108ef.png)

**Comment by baedert** [comment] 2016-02-21 19:19
The latter shouldn't happen anymore.

**Comment by IBBoard** [comment] 2016-02-21 19:29
Commit 80122fbbf368bffcfe233c03c3c7dd0bdf29c0fc?

**Comment by baedert** [comment] 2016-02-22 10:52
Aaaaand check the sizing again. It's suboptimal and not really what i'd wish from the gtk+ sizing machinery, but anyway...

**Closed** 2016-03-05 10:47 UTC
