### ISSUE TITLE
SIGSEGV in g_string_append_uri_escaped

### ISSUE THREAD

**Issue by thierry-FreeBSD** [baedert/corebird#310] opened 2015-02-11 20:52 UTC
Hello,

I ported corebird-0.9 to FreeBSD. It builds without any problem.
I run it, then click on "Request PIN", and it aborts (segfault):

Program received signal SIGSEGV, Segmentation fault.
0x0000000803fdc08f in g_string_append_uri_escaped () from /usr/local/lib/libglib-2.0.so.0

A backtrace is available at https://gist.github.com/thierry-FreeBSD/adeab235d2e00ac9537e#file-gistfile1-txt

Previously, it displays:
account_get_screen_name: assertion 'IS_ACCOUNT (self)' failed

Any idea? Have you already seen this bug on other platforms?

Best regards.

**Comment by baedert** [comment] 2015-02-13 15:36
Since you ported it yourself, can you compile it with --enable-debug (I hope this problem is reproducible?) It seems to be a problem in librest though, what version of it do you have (and... can you compile that with debugging symbols? :))

**Comment by thierry-FreeBSD** [comment] 2015-02-13 20:38
Yes, you're right, hereunder is a more detailed backtrace:

#0  0x0000000803fdf08f in g_string_append_uri_escaped () from /usr/local/lib/libglib-2.0.so.0
#1  0x00000008013ce911 in sign_hmac (proxy=0x80d1162f0, call=0x80d11e5e0, oauth_params=0x80d21ff00) at oauth-proxy-call.c:149
#2  0x00000008013ce476 in _prepare (call=0x80d11e5e0, error=0x7fffffffcb60) at oauth-proxy-call.c:292
#3  0x00000008013c7ee7 in prepare_message (call=0x80d11e5e0, error_out=0x7fffffffcc60) at rest-proxy-call.c:830
#4  0x00000008013c7bfc in rest_proxy_call_async (call=0x80d11e5e0, callback=0x8013c9610 <_rest_proxy_call_async_cb>, weak_object=0x0, 
    userdata=0x7fffffffcc50, error=0x7fffffffcc60) at rest-proxy-call.c:979
#5  0x00000008013c957d in rest_proxy_call_run (call=0x80d11e5e0, loop_out=0x0, error_out=0x7fffffffcd00) at rest-proxy-call.c:1418
#6  0x00000008013cc709 in oauth_proxy_request_token (proxy=0x80d1162f0, function=0x49906a "oauth/request_token", callback_uri=0x49907e "oob", 
    error=0x7fffffffcd00) at oauth-proxy.c:423
#7  0x0000000000457316 in account_create_widget_open_pin_request_site (self=0x80b229260) at widgets/AccountCreateWidget.c:256

I have just submitted a bug report about our librest port:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=197599

**Comment by baedert** [comment] 2015-02-14 09:53
So we can close this here since it seems to be an upstream librest (or a port) bug?

**Comment by thierry-FreeBSD** [comment] 2015-02-14 13:45
Yes, please do!

**Closed** 2015-02-14 15:08 UTC
