### ISSUE TITLE
Bug: empty <ul> dialog box upon clicking [home] or [back] during loading of previous replies on a single tweet view.

### ISSUE THREAD

**Issue by mr-blobbyyy** [baedert/corebird#766] opened 2017-09-05 11:07 UTC
Steps to reproduce:
1. in your home timeline, click on a tweet that you know has a chain of lengthy previous replies. (For example this tweet: https://twitter.com/BNONews/status/904823775929266178)
2. while the previous replies are loading beneath the current "single tweet" view, quickly press [home] or [back]
3. a "\<ul>\</ul>" dialog box appears (which doesn't appear to do anything):
![image of strange dialog box](https://i.imgur.com/gFWtqKW.png)

**Comment by Vistaus** [comment] 2017-09-05 11:24
Can't reproduce. If I follow your exact steps, I don't get a ul dialog box. Which Corebord version are you using and what distro?

**Comment by mr-blobbyyy** [comment] 2017-09-05 11:26
1.6 on Antergos xfce. That box doesn't appear if you wait for all the previous replies to load in step 2, and then click on home or back.

**Comment by baedert** [comment] 2017-09-05 11:28
That should be fixed by https://github.com/baedert/corebird/commit/86b744cda3464d96087ca60dc818f0c6218e18b3

**Comment by Vistaus** [comment] 2017-09-05 11:29
@mr-blobbyyy But I didn't wait. I followed your exact steps.

Edit: ah, I now see why. @baedert links to a commit from 4 days ago that supposedly fixes it and since I'm using Corebird from git master, I can't reproduce it as that commit is already present in my current build.

**Closed** 2017-09-05 11:34 UTC
