### ISSUE TITLE
Retweets of tweets with quoted tweet and image only show image of quoted tweet

### ISSUE THREAD

**Issue by elya5** [baedert/corebird#681] opened 2017-02-26 12:35 UTC
Here is an example with pictures 

The retweet in my timeline:
![retweet in timeline](https://cloud.githubusercontent.com/assets/4464481/23339687/decb464e-fc27-11e6-8cd3-ec7879ba93a4.png)

The retweet after I click on it:
![enlarged retweet](https://cloud.githubusercontent.com/assets/4464481/23339695/f147a77c-fc27-11e6-98f9-9525c3b2227c.png)

The original tweet in the users profile:
![original](https://cloud.githubusercontent.com/assets/4464481/23339700/0a5693ea-fc28-11e6-8f4d-97d57603c730.png)

It would be nice to have an indication of the other image in the first picture.

**Comment by IBBoard** [comment] 2017-03-13 21:00
I've not checked how it looked when you opened a single tweet, but is my pull request at #631 what you need? It looks like there's been enough changes that the pull request broke, but I'm still running the patch so I can re-apply and re-request.

**Comment by baedert** [comment] 2017-04-04 07:53
#631 is about sending them, this is just about displaying them. The rule is basically "a quote tweet can never have media attached, so if they do, ignore the quote tweet and show the media instead". It's pretty hard to find a tweet like this, and I guess I can't expect testing here so I'm going to close this until someone tells me they still have that problem or b495709f857139c86b620a682734dd71aa95911c introduced a regression.

**Closed by baedert** 2017-04-04 07:53 UTC

**Comment by IBBoard** [comment] 2017-04-04 19:30
Ah, yes, I misread it and saw similarities with the screenshots I'd posted. Sorry.
