### ISSUE TITLE
Profiles don't seem redraw after damage properly

### ISSUE THREAD

**Issue by Lyude** [baedert/corebird#327] opened 2015-03-08 17:05 UTC
This is one I've had for a while now that I just keep forgetting to report. For some reason, user's profiles don't seem to always register damage properly when you scroll up. As a result you'll usually end up getting leftover graphic artifacts, which for some reason disappear and don't reappear if you scroll down far enough, then go back up. The easiest way to trigger this seems to lower the height of the window, and scroll up and down a little bit on someone's profile page.
![screenshot from 2015-03-08 13 01 34](https://cloud.githubusercontent.com/assets/1527057/6546701/bf5470e6-c593-11e4-840f-ccd2d7031edf.png)

**Comment by baedert** [comment] 2015-03-08 17:39
Goddamn someone noticed :(

I'm pretty sure the problem is the container used for the banner (that increases in size when scrolling up), maybe together with the pixel cache.

**Comment by Lyude** [comment] 2015-03-23 14:20
It is the container increasing in size as you scroll. I reproduced it yesterday when viewing someone's replies to one of my tweets and trying to scroll up to read the rest of the tweet chain. I'm not sure if I can get it to happen again but I definitely saw it, so I'm pretty sure it's the increasing in scrolling size

**Comment by Lyude** [comment] 2015-03-24 13:47
![screenshot from 2015-03-24 09 45 42](https://cloud.githubusercontent.com/assets/1527057/6802944/ae805ed2-d20a-11e4-80ca-e8e951abe30d.png)
By the way, it definitely looks like the pixel cache has something to do with it (using GTK+ Inspector to color pixel cache)

**Comment by baedert** [comment] 2015-11-09 16:15
Okay, finally got someone to fix this in gtk+, the fix is in master and will also be in 3.18.3. Closing this. thanks for your investigation.

**Closed by baedert** 2015-11-09 16:15 UTC
