### ISSUE TITLE
Long tweets without spaces can forcibly enlarge the window to silly sizes

### ISSUE THREAD

**Issue by Lyude** [baedert/corebird#657] opened 2016-12-18 21:45 UTC
A tweet on my timeline recently triggered this fun bug:
![screenshot from 2016-12-18 16-40-16](https://cloud.githubusercontent.com/assets/1527057/21296764/ef1ac024-c540-11e6-8dab-df1eb6d5f884.png)
![screenshot from 2016-12-18 16-42-57](https://cloud.githubusercontent.com/assets/1527057/21296768/0ead3ce6-c541-11e6-9a3f-f8e5bade2cf6.png)
Tweet: https://twitter.com/0kbps/status/810600379939430400

Running off of https://github.com/baedert/corebird/commit/463141b2ff7138cf1aea314fb50a2e346eaefe53 on Wayland w/ gnome shell, using Fedora 25

**Comment by baedert** [comment] 2016-12-19 08:17
Duplicate of #514, the wrapping is everything I can do with a standard `GtkLabel`, maybe pango should just handle cases like this better.

**Closed by baedert** 2016-12-19 08:17 UTC

**Comment by IBBoard** [comment] 2017-03-18 17:03
I encountered this when someone posted a huge string of "?". Bizarrely, it appears to wrap sensible with a string of letters (see https://twitter.com/IBBTwtr/status/843142043509690368) but not question marks!
![screenshot from 2017-03-18 16-56-38](https://cloud.githubusercontent.com/assets/388582/24074240/b7facd34-0bfc-11e7-9a83-1cd2c753a5e4.png)
Is there a Pango bug already for this? Because I've not found one so far.

**Comment by baedert** [comment] 2017-03-19 19:29
> I encountered this when someone posted a huge string of "?". Bizarrely, it appears to wrap sensible with a string of letters (see https://twitter.com/IBBTwtr/status/843142043509690368) but not question marks!

I know
>  Is there a Pango bug already for this? Because I've not found one so far.

I don't now, I haven't filed one at least.

**Comment by IBBoard** [comment] 2017-03-19 19:46
I've found a relevant bug: https://bugzilla.gnome.org/show_bug.cgi?id=131625

Sounds like this case and I've seen the "break one letter from the end of a word to the next line" behaviour as well (so "test[space][long-string-of-question-marks]" didn't break at the space, it broke after the "s" and put "t[space][long-string-of-question-marks]" on the next line, despite the ridiculousness of that break pattern!)

On the plus side, one of their devs has admitted in 2015 that their line wrapping code is a bit broken! https://bugzilla.gnome.org/show_bug.cgi?id=754301#c2
