### ISSUE TITLE
Tab for Tweets of yours people like and/or retweet

### ISSUE THREAD

**Issue by glassresistor** [baedert/corebird#453] opened 2015-12-09 23:57 UTC
Right now there is no way to view other interactions besides mentions.  Retweets and likes are things I'd like to be able to see lists of without having to use the web client

**Comment by baedert** [comment] 2015-12-10 07:41
Likes are favorites and there's a tab for them. I don't really see a need for "list everything I've retweeted"? If you need that, you should favorite that tweet.

**Comment by glassresistor** [comment] 2015-12-11 05:39
Its a list of your likes, I'm wanting a list of things of people like of
yours.

On Wed, Dec 9, 2015 at 11:41 PM, baedert <notifications@github.com> wrote:

> Likes are favorites and there's a tab for them. I don't really see a need
> for "list everything I've retweeted"? If you need that, you should favorite
> that tweet.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/baedert/corebird/issues/453#issuecomment-163524649>.
>



-- 
Mikela

**Comment by baedert** [comment] 2015-12-11 08:16
I don't get it. Is this about the notifications twitter.com has again?

**Comment by glassresistor** [comment] 2015-12-11 20:17
Corebird currently doesn't provide a way to know if someone likes one of
their tweets or if someone retweets one of their tweets.

On Fri, Dec 11, 2015 at 12:17 AM, baedert <notifications@github.com> wrote:

> I don't get it. Is this about the notifications twitter.com has again?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/baedert/corebird/issues/453#issuecomment-163871994>.
>



-- 
Mikela

**Comment by glassresistor** [comment] 2015-12-11 20:23
So in the twitter docs it would be tracking these events 
https://dev.twitter.com/streaming/overview/messages-types
Events section your see these event types

User’s Tweet is liked	favorite	Liking user	Current user	Tweet
and
User’s Tweet is quoted	quoted_tweet	quoting User	Current User	Tweet

**Comment by baedert** [comment] 2015-12-11 20:39
You didn't answer my question, but I guess this is a duplicate of #317.

**Closed by baedert** 2015-12-11 20:39 UTC
