### ISSUE TITLE
Scrolling back loads oldest tweets from cache

### ISSUE THREAD

**Issue by IBBoard** [baedert/corebird#685] opened 2017-03-18 16:35 UTC
If you have Corebird open for a while and then scroll back, it will load its *oldest* block of tweets, not the ones just preceding the latest block.

Steps to recreate:
 1. Open Corebird
 1. Scroll back at least six pages-worth of tweets (so there's an obvious time difference in tweets between the newest set and the oldest)
 1. Scroll to the top
 1. Wait until Corebird refreshes and prunes its list (you'll see the scrollbar get longer as it removes the old tweets from the view)
 1. Scroll back down to the end of the tweet list so that Corebird loads older tweets

Expected behaviour: Tweets just preceding the last tweet are reloaded - i.e. if your last tweet was ~45m ago, the most recent of the newly loaded tweets is ~45-50 minutes ago.

Actual behaviour: Tweets that were the final page loaded are re-loaded - i.e. if you scrolled back six hours then there will be a tweet ~45 minutes ago and just below that a tweet ~6hrs ago, skipping all tweets in the middle with no way to load them (other than close Corebird, so it loses its cache).

Version: Git Master (build 15 minutes ago)

**Comment by Vistaus** [comment] 2017-03-18 16:48
Can't reproduce. What distro do you use?

**Comment by IBBoard** [comment] 2017-03-18 17:02
openSUSE Leap 42.2 (GTK 3.20.9), but this was a Corebird build from the Master branch. Also happens with my custom build on openSUSE Tumbleweed (GTK 3.22.8)

**Comment by IBBoard** [comment] 2017-03-18 17:12
This appeared between heartbeets when I did the "scroll back down again" part:

    (corebird:25779): corebird-DEBUG: TweetUtils.vala:487: REST Call: GET 1.1/statuses/home_timeline.json?count=28&max_id=843044333557301248&tweet_mode=extended&include_my_retweet=true&

Trying to confirm, but it looks like it might be supplying the wrong ID to the server, rather than reading the wrong bit of its cache?

**Comment by IBBoard** [comment] 2017-03-18 18:01
Something definitely appears to be odd. I made the following change to add some debug:

    diff --git a/src/CbTweetModel.c b/src/CbTweetModel.c
    index 96078f2..706502a 100644
    --- a/src/CbTweetModel.c
    +++ b/src/CbTweetModel.c
    @@ -662,11 +671,15 @@ cb_tweet_model_add (CbTweetModel *self,
         {
           insert_sorted (self, tweet);
     
    -      if (tweet->id > self->max_id)
    +      if (tweet->id > self->max_id) {
    +        g_debug("Added tweet %u - new max (was %u)", tweet->id, self->max_id);
             self->max_id = tweet->id;
    +      }
     
    -      if (tweet->id < self->min_id)
    +      if (tweet->id < self->min_id) {
    +        g_debug("Added tweet %u - new min (was %u)", tweet->id, self->min_id);
             self->min_id = tweet->id;
    +      }
         }
     }

And the output includes:

    (corebird:13769): corebird-DEBUG: Added tweet 618061824 - new min (was 806666240)
    (corebird:13769): corebird-DEBUG: Added tweet 253018112 - new min (was 618061824)
    (corebird:13769): corebird-DEBUG: Added tweet 1012195328 - new min (was 253018112)

The first update is correct (618,061,824 < 806,666,240), as is the second (253,018,112 < 618,061,824) but the third line makes no sense because 1,012,195,328 > 253,018,112! It shouldn't be setting a new min, but it is. I can't tell why at the moment, as both the `tweet->id` and the `self->min_id` are gint64. 64-bit ints should be more than enough to store the IDs without weird overflow behaviour.

**Comment by IBBoard** [comment] 2017-03-18 18:59
I did some poking and I think that should fix it. Somewhen in the move from Vala to C for the tweet model, the update call got removed. That means that the min_id gets older and older as you scroll back, but never gets moved back up when it prunes. This seems to fix it for me.

**Comment by kajzersoze** [comment] 2017-03-18 22:30
Dunno if this is related, it really well could be, but I have a problem where if you leave corebird opened for some time, maybe 10 minutes, maybe less I'm not sure, anyway when you click on some tweet (doesn't matter which one, old or new) there is 0 Retweets and 0 Favorites shown, when you check those tweets via browser or via something else you can see that there are plenty of both.
Problem no.2 is that you can't favorite those tweets, nothing happens when you do, however if you right click on a tweet and fav from there then it works and 0 Retweets and 1 Favorite is shown, really weird.
The only way to get out from that mode is to close corebird and start it again.
Debug isn't showing anything regarding this.

**Comment by IBBoard** [comment] 2017-03-19 09:32
Yeah, I'd have said it was unrelated. This was clearly about a "what is the last ID I'm showing" value not being updated and resulting in the right set of previous tweets being retrieved. Your first problem sounds like Corebird just kept the counts from when it first fetched the tweet, and the second one sounds like a UI issue (because Corebird would pop up a warning if it was Twitter rejecting the RT/Fav command)

**Comment by Vistaus** [comment] 2017-03-19 09:45
@kajzersoze That I can reproduce. **BUT** I doubt that that's a Corebird issue as the same issue happens every now and then in the official Twitter client on my phone (once in a while even if I have it open for like 2 minutes or so). So it's most likely a Twitter issue.

**Comment by IBBoard** [comment] 2017-03-19 10:15
Nope, fairly sure it is a Corebird issue. Check my patch.

Without my patch Corebird starts with tweet 100, loads back to 90 and sets that as min, loads back to 80 and sets that as min, loads back to 70 and sets that as min, then you scroll to the top and it truncates to 90 but leaves min as 70. If you scroll back down then it explicitly sends a request to Twitter saying "give me all tweets in this feed before tweet 70". This means you get a big gap of missing tweets - from 89 to 70.

With my patch Corebird starts with tweet 100, loads back to 90 and sets that as min, loads back to 80 and sets that as min, loads back to 70 and sets that as min, then you scroll to the top and it truncates to 90 *and* resets min to 90. If you scroll back down then it explicitly sends a request to Twitter saying "give me all tweets in this feed before tweet 90". This means you get all of the tweets without a gap.

(Note: IDs are actually 64-bit numbers, but I thought it'd be easier to work sub-100 😉)

**Comment by Vistaus** [comment] 2017-03-19 11:14
@IBBoard "Nope, fairly sure it is a Corebird issue. Check my patch."

Nope, re-read my post. I responded to @kajzersoze's issues, not your issue. His issues are a Twitter issue, your issue is probably a Corebird issue.

**Comment by kajzersoze** [comment] 2017-03-19 12:03
@Vistaus Could be, though I've only seen it with Corebird.
To test that I just opened at the same time Corebird and Tweetdeck, after few minutes that issue happened with Corebird, Tweetdeck is still good.

**Comment by Vistaus** [comment] 2017-03-19 12:11
@kajzersoze But like I said: I experience it sometimes with the official Twitter client on my phone as well as in Corebird. So it's gotta be a Twitter issue, else the official client would be fine. It could very well be that you don't experience it with, say, Tweetdeck. Bugs don't always occur for everyone ;)

**Comment by kajzersoze** [comment] 2017-03-19 12:26
@Vistaus hehe, but there lies the problem, if one client has that bug and the other doesn't then I don't see how that is a Twitter issue, of course it might be, I'm not 100% sure, I still have Tweetdeck open and it's still w/o issues, Ima leave it until it happens, well at least a couple of hours more, if it doesn't happen in couple of hours from now then I would say that it's definitely not a Twitter issue.

**Comment by kajzersoze** [comment] 2017-03-19 19:21
@IBBoard with patch from your PR I always get "Now" as time of a tweet, not right away, but if you leave it open for some time and then scroll to the top all tweets has "Now", instead "34min" "1hr" "2hr" etc.
I guess there was a reason for commenting that line.

**Comment by IBBoard** [comment] 2017-03-19 19:27
@Vistaus Sorry, managed to completely blank the name there!

@kajzersoze I've not noticed that, but I'll keep an eye out. Given what it changes then I'm not clear how it'd trigger that behaviour, though. The function that now gets called just alters which tweet ID is the last one (and prunes hidden tweets). It doesn't touch timestamps or rendering to the UI.

**Comment by IBBoard** [comment] 2017-03-19 21:01
@kajzersoze I did see this on my build if I left Corebird at the top. I then switched to a vanilla build and I still see it happen at times, so I think it is a standard Corebird problem. Sometimes new tweets coming in causes it to refresh the timestamps (but not always). Unless someone can prove otherwise, I don't think my one-line patch is causing that behaviour.

**Comment by kajzersoze** [comment] 2017-03-19 21:39
@IBBoard Well okay, I'm not sure if I ever saw that behaviour before, I think I didn't but who knows.
I'm back to master now so if I see that again I'll report it here.

**Comment by kajzersoze** [comment] 2017-03-20 18:54
@IBBoard Yeah you were right, I just had that "Now" bug without your patch, so it happens anyway.

Something is going on with this, there are several issues (bugs) that share common factor, that's why I said some of the other issues are related to the one reported here.

**Comment by baedert** [comment] 2017-03-20 19:48
Try the "Now" problem again with master, I've fixed one pretty stupid problem about that today.

**Comment by kajzersoze** [comment] 2017-03-21 20:10
@baedert That one is kinda hard to catch, but I didn't see it today.

More pressing problem is not being able to see replies, favs and RT's after just few minutes.
When that happens you can't fav a tweet as well.
You can, if you right click on a tweet and then fav it, then it shows 0 RTs and 1 Fav (in reality there are more) 
While I'm at it, there's also one more problem, sometimes when you leave it open for some time, it auto-scroll to the top (auto scroll is disabled in settings) and when you scroll down only few tweets are shown (no more than 10) and you can't go any further. The only way out of that is to exit from corebird and start it again.

**Comment by IBBoard** [comment] 2017-03-21 20:35
@kajzersoze I think at least three or four of these need separate tickets, as we're basically certain that they're unrelated to my original problem.

**Comment by kajzersoze** [comment] 2017-03-21 20:39
You're right, sorry about that, I'll create new one.

**Comment by baedert** [comment] 2017-03-28 13:45
The original issue should be fixed now that #691 is merged.

**Closed by baedert** 2017-03-28 13:45 UTC
