### ISSUE TITLE
Core bird does stops retriving messages after starting up

### ISSUE THREAD

**Issue by teroz** [baedert/corebird#684] opened 2017-03-16 06:04 UTC
Corebird starts fine but will not retrive any more messages after the intitial ones. I am running 
Kali GNU/Linux Rolling on an i7 with all the RAM in the world
![screenshot from 2017-03-16 07-55-21](https://cloud.githubusercontent.com/assets/853846/23983880/22360680-0a1f-11e7-94b8-c8e77bf523d2.png)

**Comment by baedert** [comment] 2017-03-16 07:23
Can't help without the console output. Preferrable with `G_MESSAGES_DEBUG=all`. And even then I can't really help, it's just restarting the streaming connection on a regular basis until the server responds with a heartbeat.

**Comment by teroz** [comment] 2017-03-16 10:39
hmmmmm @baedert 

(corebird:18389): corebird-WARNING **: UserStream.vala:216: buf(teroz) == NULL. Starting timeout...
(corebird:18389): corebird-DEBUG: Account.vala:504: Add 0 disabled_rts ids
(corebird:18389): GdkPixbuf-DEBUG: gdk_pixbuf_from_pixdata() called on:
(corebird:18389): GdkPixbuf-DEBUG:      Encoding raw
(corebird:18389): GdkPixbuf-DEBUG:      Dimensions: 32 x 32
(corebird:18389): GdkPixbuf-DEBUG:      Rowstride: 128, Length: 4120
(corebird:18389): GdkPixbuf-DEBUG:      Copy pixels == false
(corebird:18389): GdkPixbuf-DEBUG: gdk_pixbuf_from_pixdata() called on:
(corebird:18389): GdkPixbuf-DEBUG:      Encoding raw
(corebird:18389): GdkPixbuf-DEBUG:      Dimensions: 64 x 64
(corebird:18389): GdkPixbuf-DEBUG:      Rowstride: 256, Length: 16408
(corebird:18389): GdkPixbuf-DEBUG:      Copy pixels == false
(corebird:18389): corebird-DEBUG: UserStream.vala:183: Restarting stream (reason: network available (timeout))
(corebird:18389): corebird-DEBUG: UserStream.vala:159: STOPPING STREAM FOR teroz
(corebird:18389): corebird-DEBUG: UserStream.vala:129: Starting stream for teroz

(corebird:18389): corebird-WARNING **: UserStream.vala:216: buf(teroz) == NULL. Starting timeout...
(corebird:18389): corebird-DEBUG: UserStream.vala:183: Restarting stream (reason: network available (timeout))
(corebird:18389): corebird-DEBUG: UserStream.vala:159: STOPPING STREAM FOR teroz
(corebird:18389): corebird-DEBUG: UserStream.vala:129: Starting stream for teroz

(corebird:18389): corebird-WARNING **: UserStream.vala:216: buf(teroz) == NULL. Starting timeout...
(corebird:18389): corebird-DEBUG: UserStream.vala:183: Restarting stream (reason: network available (timeout))
(corebird:18389): corebird-DEBUG: UserStream.vala:159: STOPPING STREAM FOR teroz
(corebird:18389): corebird-DEBUG: UserStream.vala:129: Starting stream for teroz

(corebird:18389): corebird-WARNING **: UserStream.vala:216: buf(teroz) == NULL. Starting timeout...
(corebird:18389): corebird-DEBUG: UserStream.vala:183: Restarting stream (reason: network available (timeout))
(corebird:18389): corebird-DEBUG: UserStream.vala:159: STOPPING STREAM FOR teroz
(corebird:18389): corebird-DEBUG: UserStream.vala:129: Starting stream for teroz
![screenshot from 2017-03-16 12-29-09](https://cloud.githubusercontent.com/assets/853846/23992417/80f08f30-0a45-11e7-967c-47ff329b6486.png)

**Comment by Vistaus** [comment] 2017-03-19 21:23
I think this is caused by the limited streaming API for 3rd party clients.

**Comment by baedert** [comment] 2017-03-20 10:12
That's basically the case I can't do anything about; the connection just returns NULL and restarts itself over and over again.

**Comment by baedert** [comment] 2017-06-17 05:40
Closing this then.

**Closed by baedert** 2017-06-17 05:40 UTC
