### ISSUE TITLE
Image preview always cropped square

### ISSUE THREAD

**Issue by hfiguiere** [baedert/corebird#340] opened 2015-03-28 17:05 UTC
The  Image preview always cropped square. This doesn't make sense. I should should the image in the aspect ratio. Scaled down eventually for the screen size. But not with systemic scrollbars.

**Comment by hoyang** [comment] 2015-04-30 05:39
See public static const int HEIGHT in MultiMediaWidget.vala

**Comment by hoyang** [comment] 2015-04-30 05:40
@hfiguiere See public static const int HEIGHT in MultiMediaWidget.vala

**Comment by hfiguiere** [comment] 2015-04-30 20:26
How does that matter to the user what's in the source?

**Comment by hfiguiere** [comment] 2015-04-30 20:27
Beside the fact that this mean it assume the screen size. Like in the 80s....

**Comment by IBBoard** [comment] 2015-12-12 19:59
Can you close this one now @baedert? It seems to work for me in Git Master.

**Comment by baedert** [comment] 2015-12-12 20:04
I thought this was about the dialog that shows the image in full size.

**Comment by IBBoard** [comment] 2015-12-12 20:08
Ah, sorry. I was checking back through image-related ones and saw "preview" and thought "shrunken preview image below post". If this is about the popup then it covers an enhancement I was going to raise (if I've read it right): When you click on the image, make the image in the pop-up box scale, with a button to show at full size (or full-screen, if it is bigger than the monitor!).

Especially on newer Gnome with the auto-hiding scrollbars then it isn't always clear when there's more to scroll to in the current box.

**Comment by facundobatista** [comment] 2017-05-24 15:19
I have the same problem (Corebird 1.5, under Ubuntu Xenial, installed from the Snap store).

All images I open from my timeline are cropped and I need to start panning to see them completely...

**Comment by Vistaus** [comment] 2017-05-24 17:54
@facundobatista No problem here (Corebird 1.5 on Solus):

![screenshot from 2017-05-24 19 53 08](https://cloud.githubusercontent.com/assets/1716229/26417907/032d336e-40aa-11e7-98a3-b862f6ae7d1f.png)

**Comment by facundobatista** [comment] 2017-05-24 20:16
For reference, see these three screenshots: 

1. just showing the interface, with the image I will click on
1. after clicking in the image, where you can see that the image is not fully shown
1. a little of resizing and panning, to be sure that "there is more image to see"

![corebird1](https://cloud.githubusercontent.com/assets/184060/26418200/b9869aec-4091-11e7-9a83-708afb4d7c7c.png)
![corebird2](https://cloud.githubusercontent.com/assets/184060/26418201/b98923ac-4091-11e7-861c-ad8516edf8d3.png)
![corebird3](https://cloud.githubusercontent.com/assets/184060/26418202/b9951946-4091-11e7-82f3-b23b151a7bf6.png)

**Comment by Vistaus** [comment] 2017-05-24 20:24
@facundobatista Ah, I see. I was confused because of the wording "image preview". But you're referring to the image viewer. In that case, I can confirm this issue 😉

**Comment by baedert** [comment] 2017-05-24 20:50
I don't really see the problem, you know there's more to the image because you've seen the downscaled version and those dashed line at the edges of the window indicate that you can scroll.

**Comment by facundobatista** [comment] 2017-05-24 21:05
@baedert the problem is that the opened image should be shown entirely, why to hide part of it and force me to scroll?

**Comment by baedert** [comment] 2017-05-24 21:07
Because it doesn't fit in your screen (at least according to the extremely smart heuristics in use here) in full size and it seem pointless to show another downscaled version after you just clicked on one?

**Comment by facundobatista** [comment] 2017-05-24 21:23
I lost track of the other image to check that, but see this new one...

Here is the Corebird showing the image between the texts:

![corebird1](https://cloud.githubusercontent.com/assets/184060/26426007/3d1dcee6-40ad-11e7-8768-9cb4396ed4ba.png)

Now I clicked, it opened the image, but check that it's not shown entirely:

![corebird2](https://cloud.githubusercontent.com/assets/184060/26426006/3d1c08ea-40ad-11e7-9883-073f6c9f55cc.png)

Here I expanded the borders, and see that I can see the all the image!! (even a little of empty space after I expanded the borders too much)

![corebird3](https://cloud.githubusercontent.com/assets/184060/26426005/3d1ba9b8-40ad-11e7-8b92-24c310735667.png)

However, then I downloaded the image and checked it: its size is 2120x1440, while my screen is 1920x1080.

So, the image really does NOT fit into my screen, but it's not only shown trimmed, but also downscaled!!

Two paths here:

- If you'll downscale it even when I click on it, show the full image!

- If you will show the image partially, don't downscale it!

**Comment by facundobatista** [comment] 2017-05-24 21:26
I lost track of the other image to check that, but see this new one...

Here is the Corebird showing the image between the texts:

![corebird1](https://cloud.githubusercontent.com/assets/184060/26426007/3d1dcee6-40ad-11e7-8768-9cb4396ed4ba.png)

Now I clicked, it opened the image, but check that it's not shown entirely:

![corebird2](https://cloud.githubusercontent.com/assets/184060/26426006/3d1c08ea-40ad-11e7-9883-073f6c9f55cc.png)

Here I expanded the borders, and see that I can see the all the image!! (even a little of empty space after I expanded the borders too much)

![corebird3](https://cloud.githubusercontent.com/assets/184060/26426005/3d1ba9b8-40ad-11e7-8b92-24c310735667.png)

However, then I downloaded the image and checked it: its size is 2120x1440, while my screen is 1920x1080.

So, the image really does NOT fit into my screen, but it's not only shown trimmed, but also downscaled!!

Two paths here:

- If you'll downscale it even when I click on it, show the full image!

- If you will show the image partially, don't downscale it!

**Comment by baedert** [comment] 2017-05-24 21:31
It's not shown downscaled, twitter just gives us a smaller version of the image which is shown here, but downloading it downloads the `:orig` version which is usually larger.

**Comment by facundobatista** [comment] 2017-05-24 21:32
@baedert so, if the first "smaller version" which is shown there actually fits in the screen, why not showing it entirely?

**Comment by baedert** [comment] 2017-05-24 21:50
Dunno, the window shouldn't take up the entire screen and the current code uses 70% of the screen size: https://github.com/baedert/corebird/blob/master/src/CbMediaImageWidget.c#L117

**Comment by facundobatista** [comment] 2017-05-25 17:07
Maybe we should change that 0.7 and make it 1 (well, remove the product), because of the following reasoning: if I'm clicking the image, I want to see the image, why show me at most 70% of the screen? I don't want to see the stuff below, I want to see the image, please use all the screen if you must!

**Comment by IBBoard** [comment] 2017-07-08 18:27
Here's a patch that I'm using now that uses 95% of the screen (to allow for desktop environment menu bars etc - like the top bar in Gnome) *and* doesn't put images that are greater than 1344 pixels wide or 756 pixels high into a 800×600 box on a 1080p monitor:

https://build.opensuse.org/package/view_file/home:IBBoard:desktop/corebird/corebird-max-image-viewer-size.patch?expand=1

(Also, I'm not sure whether Twitter ever serves bigger than 1200×900 by default, so it might not always hit full screen)

**Closed** 2017-12-30 18:27 UTC
