### ISSUE TITLE
Preserve image ratio in embedded tweets

### ISSUE THREAD

**Issue by guerda** [baedert/corebird#402] opened 2015-09-21 16:41 UTC
Version 1.0.1, Fedora 22 x64

Currently, images are drawn without respecting the original image ration, if shown in a tweet list:
It depends on Corebird's window size:
![corebird_image_distorted](https://cloud.githubusercontent.com/assets/230782/9998080/f8925070-608f-11e5-8f1b-d6de64c00fc7.png)
![corebird_image_correct](https://cloud.githubusercontent.com/assets/230782/9998079/f88cc3d0-608f-11e5-9975-05eac952b91c.png)

If you then open the image, it is shown correctly. 
A suggestion would be to change the selected image crop on window resize or just pad it with background.

**Comment by baedert** [comment] 2015-09-21 16:46
Search in the bug tracker for similar bugs if you want to read a discussion, I'm too lazy atm (and reading this over and over again doesn't help).

**Comment by guerda** [comment] 2015-09-21 16:53
So it seems to be a duplicate of #340 and #278 and #199 and #198 ?
As far as I understood, the image is only then correctly rendered, if you didn't maximize the window or slightly changed the size.
Wouldn't be padding a simple fix for this?

**Comment by baedert** [comment] 2015-09-21 17:05
I think so. I have absolutely no clue what #340 is about, but my guess would be rather the dialog containig the full view (otherwise "systemic scrollbars" doesn't make sense). #199 is 99% off-topic with a single on-topic comment, which is the inital one. This is a duplicate of #278 and #198, yes.

Just adding padding doesn't fix a single thing. It just looks as ugly and does not have any upside.

**Closed** 2015-09-26 17:58 UTC
