### ISSUE TITLE
Receiving reply temporarily hangs Gnome Shell

### ISSUE THREAD

**Issue by jc00ke** [baedert/corebird#697] opened 2017-04-04 23:00 UTC
Kinda hard to reproduce, but at times the whole UI hangs and then I get the notification for a reply. I'm running 1.4.1-1 from `universe/net`.

Ideas on how to debug?

**Comment by baedert** [comment] 2017-04-05 06:55
For how long does it hang?

> Ideas on how to debug?

Well you could build with debugging enabled and just shove some mention json to corebird via dbus, like https://github.com/baedert/corebird-debug-tool is doing, but that only contains json for me.

I guess just using `notify-send` doesn't reproduce the issue? What gnome-shell version are you using?

**Comment by jc00ke** [comment] 2017-04-05 20:05
It hangs for 5s or so.

`notify-send` works OK, no hanging. I'm using Gnome Shell 3.24.

**Comment by jc00ke** [comment] 2017-04-05 20:07
How do you send the debug json in via `dbus`?

**Comment by baedert** [comment] 2017-04-05 20:13
>  I'm using Gnome Shell 3.24.

Ah, I'm still using 3.22.

If you have corebird compiled with debugging enabled, you can just paste the tweet json (e.g. from a tweet causing such a hang) into a file and then use the `corebird-test.sh` file from the repository I linked to send it like `./corebird-test.sh my-reply.json`. It should then be handled like any other tweet json arriving on the streaming connection. You can get such a json description if you just focus a tweet and press `k` (also only when compiled with debugging enabled (it will be printed to the terminal).

When it happens, it would be nice to see what the journal and/or corebird prints.

**Comment by jc00ke** [comment] 2017-04-07 16:11
Happy to debug. Do you have a definitive list of dependencies so that I can get the project compiling? I started one in [the wiki](https://github.com/baedert/corebird/wiki/Compiling-on-Ubuntu).

**Comment by baedert** [comment] 2017-04-07 16:21
libgee is not a dependency. I otherwise don't have a comprehensive list other than the ones mentioned in the readme

**Comment by baedert** [comment] 2017-04-07 17:08
Looks like this bug might be related: https://bugzilla.gnome.org/show_bug.cgi?id=781038

**Comment by jc00ke** [comment] 2017-04-08 20:10
This tweet will sometimes take up to 8s to process through `gdbus`
<details>

```javascript
{
  "created_at": "Fri Apr 07 02:43:27 +0000 2017",
  "id": 850177169758101500,
  "id_str": "850177169758101504",
  "text": "@jc00ke Its a dark day in a dark time.",
  "truncated": false,
  "entities": {
    "hashtags": [],
    "symbols": [],
    "user_mentions": [
      {
        "screen_name": "jc00ke",
        "name": "Jesse Cooke",
        "id": 14425908,
        "id_str": "14425908",
        "indices": [
          0,
          7
        ]
      }
    ],
    "urls": []
  },
  "source": "<a href=\"https://about.twitter.com/products/tweetdeck\" rel=\"nofollow\">TweetDeck</a>",
  "in_reply_to_status_id": 850177115139919900,
  "in_reply_to_status_id_str": "850177115139919872",
  "in_reply_to_user_id": 712096606435213300,
  "in_reply_to_user_id_str": "712096606435213312",
  "in_reply_to_screen_name": "steppedpyramids",
  "user": {
    "id": 712096606435213300,
    "id_str": "712096606435213312",
    "name": "stepped pyramids",
    "screen_name": "steppedpyramids",
    "location": "the invincible sun",
    "description": "out with the heart and the infamy",
    "url": "https://t.co/KN1r5QQFP9",
    "entities": {
      "url": {
        "urls": [
          {
            "url": "https://t.co/KN1r5QQFP9",
            "expanded_url": "http://steppedpyramids.com",
            "display_url": "steppedpyramids.com",
            "indices": [
              0,
              23
            ]
          }
        ]
      },
      "description": {
        "urls": []
      }
    },
    "protected": false,
    "followers_count": 42,
    "friends_count": 54,
    "listed_count": 2,
    "created_at": "Tue Mar 22 02:00:35 +0000 2016",
    "favourites_count": 606,
    "utc_offset": -25200,
    "time_zone": "Pacific Time (US & Canada)",
    "geo_enabled": false,
    "verified": false,
    "statuses_count": 1217,
    "lang": "en",
    "contributors_enabled": false,
    "is_translator": false,
    "is_translation_enabled": false,
    "profile_background_color": "000000",
    "profile_background_image_url": "http://abs.twimg.com/images/themes/theme1/bg.png",
    "profile_background_image_url_https": "https://abs.twimg.com/images/themes/theme1/bg.png",
    "profile_background_tile": false,
    "profile_image_url": "http://pbs.twimg.com/profile_images/712097178043330560/-voNlu9K_normal.jpg",
    "profile_image_url_https": "https://pbs.twimg.com/profile_images/712097178043330560/-voNlu9K_normal.jpg",
    "profile_link_color": "FAB81E",
    "profile_sidebar_border_color": "000000",
    "profile_sidebar_fill_color": "000000",
    "profile_text_color": "000000",
    "profile_use_background_image": false,
    "has_extended_profile": true,
    "default_profile": false,
    "default_profile_image": false,
    "following": false,
    "follow_request_sent": false,
    "notifications": false,
    "translator_type": "none"
  },
  "geo": null,
  "coordinates": null,
  "place": null,
  "contributors": null,
  "is_quote_status": false,
  "retweet_count": 0,
  "favorite_count": 2,
  "favorited": false,
  "retweeted": false,
  "lang": "en"
}
```
</details>

This tweet goes through every time very fast

<details>

```javascript
{
  "created_at": "Sat Apr 08 18:32:40 +0000 2017",
  "id": 850778435412742100,
  "id_str": "850778435412742146",
  "text": "@jc00ke the key works in addition to your password. So if I take yours, I can’t log in unless I also know your password",
  "truncated": false,
  "entities": {
    "hashtags": [],
    "symbols": [],
    "user_mentions": [
      {
        "screen_name": "jc00ke",
        "name": "Jesse Cooke",
        "id": 14425908,
        "id_str": "14425908",
        "indices": [
          0,
          7
        ]
      }
    ],
    "urls": []
  },
  "source": "<a href=\"http://sites.google.com/site/yorufukurou/\" rel=\"nofollow\">YoruFukurou</a>",
  "in_reply_to_status_id": 850764468879368200,
  "in_reply_to_status_id_str": "850764468879368192",
  "in_reply_to_user_id": 14425908,
  "in_reply_to_user_id_str": "14425908",
  "in_reply_to_screen_name": "jc00ke",
  "user": {
    "id": 55525953,
    "id_str": "55525953",
    "name": "Pinboard",
    "screen_name": "Pinboard",
    "location": "San Francisco",
    "description": "veni vidi tweeti",
    "url": "http://t.co/qOHjNexLMt",
    "entities": {
      "url": {
        "urls": [
          {
            "url": "http://t.co/qOHjNexLMt",
            "expanded_url": "http://pinboard.in",
            "display_url": "pinboard.in",
            "indices": [
              0,
              22
            ]
          }
        ]
      },
      "description": {
        "urls": []
      }
    },
    "protected": false,
    "followers_count": 38950,
    "friends_count": 23,
    "listed_count": 2072,
    "created_at": "Fri Jul 10 10:24:12 +0000 2009",
    "favourites_count": 109,
    "utc_offset": 10800,
    "time_zone": "Bucharest",
    "geo_enabled": false,
    "verified": false,
    "statuses_count": 35918,
    "lang": "en",
    "contributors_enabled": false,
    "is_translator": false,
    "is_translation_enabled": false,
    "profile_background_color": "FFFFFF",
    "profile_background_image_url": "http://abs.twimg.com/images/themes/theme1/bg.png",
    "profile_background_image_url_https": "https://abs.twimg.com/images/themes/theme1/bg.png",
    "profile_background_tile": false,
    "profile_image_url": "http://pbs.twimg.com/profile_images/494414965/logo_normal.png",
    "profile_image_url_https": "https://pbs.twimg.com/profile_images/494414965/logo_normal.png",
    "profile_link_color": "0084B4",
    "profile_sidebar_border_color": "BDDCAD",
    "profile_sidebar_fill_color": "FFFFFF",
    "profile_text_color": "333333",
    "profile_use_background_image": false,
    "has_extended_profile": false,
    "default_profile": false,
    "default_profile_image": false,
    "following": true,
    "follow_request_sent": false,
    "notifications": false,
    "translator_type": "none"
  },
  "geo": null,
  "coordinates": null,
  "place": null,
  "contributors": null,
  "is_quote_status": false,
  "retweet_count": 0,
  "favorite_count": 0,
  "favorited": false,
  "retweeted": false,
  "lang": "en"
}
```
</details>

**Comment by baedert** [comment] 2017-04-10 07:41
Meh, doesn't hang for me unfortunately :(

**Comment by baedert** [comment] 2017-04-10 07:45
Aaaha. I can reproduce the short hang here, but it's more like 1 or 2 seconds. Happens only when I have gnome-software installed though.

**Comment by baedert** [comment] 2017-04-24 13:24
Hmm, now that I have 3.24 system-wide, I don't seem to be able to reproduce it anymore.

**Comment by baedert** [comment] 2017-06-10 11:16
Is this still a problem (since the linked upstream gnome-shell bug report also contains a comment mentioning that it's gone)?

**Comment by jc00ke** [comment] 2017-06-13 03:32
Hmm, tricky to reproduce. I compiled 66ab39b and the first time I ran `./corebird-test.sh jc00ke-mention2-pretty.json` it hung for 5s, but not any of the subsequent times.

I did notice that if I ran `./corebird-test.sh jc00ke-mention2-pretty.json` more than once while the UI was on the main timeline view the app would crash.

```
⋊> ~/p/corebird-debug-tool on master ⨯ ./corebird-test.sh jc00ke-mention2-pretty.json                                                                                                 20:27:39()
⋊> ~/p/corebird-debug-tool on master ⨯ ./corebird-test.sh jc00ke-mention2-pretty.json                                                                                                 20:27:47
Error: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
⋊> ~/p/corebird-debug-tool on master ⨯                                                                                                                                                20:27:49
```

```
corebird:ERROR:CbTweetModel.c:230:insert_sorted: assertion failed: (insert_pos != -1)
fish: “./src/corebird” terminated by signal SIGABRT (Abort)
```

I'll run it for the next few days in debug mode and see if I can find another reply that triggers the delay. It was definitely there the first time though.

**Comment by baedert** [comment] 2017-06-14 08:13
Do you have any gnome shell extensions installed?

**Comment by jc00ke** [comment] 2017-06-14 13:51
I do, at the bottom of https://github.com/jc00ke/scripts/blob/master/setup.sh

**Comment by baedert** [comment] 2017-06-14 14:22
Hmm nope, still can't reproduce in a 17.04 VM with all those extensions installed.

**Comment by jc00ke** [comment] 2017-06-14 15:27
Hmm, I'll give it a bit more time to see if I can reproduce the hang. If I can't, I'll close.

**Comment by baedert** [comment] 2017-08-19 06:39
I'm going to close this one now, if it still happens (or ever happens again), please open a bug against gnome-shell instead, thanks.

**Closed** 2017-08-24 10:21 UTC
Labels: bug

**Comment by towo** [comment] 2017-11-15 14:50
FYI, this seems to be a general issue not related to corebird; I'm experiencing this behaviour in weird circumstances where corebird wasn't involved. If I could have a list of @jc00ke's extensions to compare likely culprits, that'd be great.

**Comment by jc00ke** [comment] 2017-11-15 16:18
@towo I'm between laptops so I'm borrowing an old MBP. I don't have an ETA on running Linux again (well, I'm hoping early next year) so don't wait for me and my extensions 😉
